### ISSUE TITLE
geom_weather not producing weather icons

### ISSUE THREAD

**Issue by sactyr** [dreamRs/weather#1]
Hi first thank you for this package. I am having several issues with producing the weather icons as intended. 

Installed dev version with
```
devtools::install_github("dreamRs/weather", dependencies = TRUE, force = TRUE)
```

Issues:
- geom_weather not producing icons:

### 1st Example
```
library(ggplot2)
library(weather)

df <- data.frame(
  hour = seq(as.POSIXct("2017-04-11"), by = "6 hour", length.out = 5),
  temperature = c(5, 4, 12, 10, 6),
  weather = c("night-clear", "day-rain-mix", 
              "day-cloudy", "day-sunny",
              "night-alt-cloudy")
)

ggplot(data = df) + 
  geom_line(aes(hour, temperature)) +
  geom_weather(aes(hour, temperature, weather = weather)) + 
  theme_minimal()
```

Plot output:
![image](https://user-images.githubusercontent.com/5043835/129662428-8b003a58-aa39-4e1a-a0a2-d5c98044a9cd.png)

### 2nd Example
```
library(ggplot2)
library(weather)

ggplot(data = paris) +
  geom_weather(aes(hour, temperature, weather = weather)) +
  theme_minimal()

# With colors
hours <- as.POSIXlt(paris$hour)$hour
paris$color <- ifelse(
  hours > 7 & hours < 21,
  "day",
  "night"
)
ggplot(data = paris) +
  geom_weather(aes(
    hour, temperature,
    weather = weather,
    color = color
  )) +
  scale_color_manual(values = c(
    "day" = "darkgoldenrod3",
    "night" = "gray20"
  )) +
  theme_minimal()
```
Plot output:
![image](https://user-images.githubusercontent.com/5043835/129664508-ce147f3f-7326-4249-b40d-39a68838d16f.png)

However the following lines work:
```
weather_icon("day-sunny")
```
```
view_all_icons()
```
```
library(shiny)

  ui <- navbarPage(
    title = "App Title",
    tabPanel(
      title = "Plot", icon = weather_icon("sunrise"),
      actionButton("go", "a button", icon = weather_icon("day-rain"))
    ),
    tabPanel("Summary", icon = weather_icon("cloud")),
    tabPanel("Table", icon = weather_icon("tornado"))
  )

  server <- function(input, output, session) {

  }

  shinyApp(ui, server)
```

I think there could be a bug within geom_weather but I am not sure. Would love for this to be fixed, if that's the case. TIA

**Comment by pvictor** [comment]
Thanks for reporting this. It should be fixed if you re-install from GitHub.
This was due to a S3 method incorrectly exported in the NAMESPACE.

Victor

**Comment by sactyr** [comment]
Thank you Victor, it works great now. Just a quick question, the icons look a bit jagged on ggplot but not if I call weather::view_all_icons(), is there a way to increase the sharpness on ggplot plots?

**Comment by pvictor** [comment]
Yes that depends on the device used to render the plot. I don't know if plot pane in RStudio can be configured.
If you export your plot in PDF it should render nicely, with PNG you have to play with parameters:

```r
# correct file dimension but poor rendering
ggsave(
  filename = "poor.png",
  plot = p, 
  device = "png", 
  dpi = 72, 
  width = 800,
  height = 500, 
  units = "px",
  scale = 1, 
  bg = "white"
)

# with better dpi, have to augment scale
ggsave(
  filename = "good.png",
  plot = p, 
  device = "png", 
  dpi = 320, 
  width = 800, 
  height = 500, 
  units = "px",
  scale = 5, 
  bg = "white"
)
```
