### ISSUE TITLE
weather_icon in plotly

### ISSUE THREAD

**Issue by sactyr** [dreamRs/weather#2]
Hey guys, having some trouble with implementing weather icons in plotly (both in shiny and non-shiny context). Reprex:

```
df <- data.frame(
        x = 1:3
        ,y = 1
        ,wthr = c("day-cloudy", "rain", "rain")
      )

plot_ly(
        data = df
        ,x = ~x
        ,y = ~y
        ,text = ~lapply(X = wthr, FUN = function(x) {
          weather_icon(x, size = "40px")
        })
      ) %>% add_text(textfont = list(family = "weathericons"))
```

![Rplot](https://user-images.githubusercontent.com/5043835/182530654-d7414920-1dfa-4533-b64a-f05ed1fc6141.png)

I have also tried using ggplot + geom_weather:

```
p <- ggplot(data = df) +
  geom_weather(
    aes(
      x = x
      ,y = y
      ,weather = wthr
    )
  )

ggplotly(p)

Warning message:
In geom2trace.default(dots[[1L]][[1L]], dots[[2L]][[1L]], dots[[3L]][[1L]]) :
  geom_GeomWeather() has yet to be implemented in plotly.
  If you'd like to see this geom implemented,
  Please open an issue with your example code at
  https://github.com/ropensci/plotly/issues
```

Any chance weather_icon could work natively in plotly similar to my first method above? Thanks

**Comment by sactyr** [comment]
I had a go with using unicode (found via `weather_icon_df`) but I am getting characters that look Chinese. Perhaps I am not appending `f00d` et al with the correct unicode prefix i.e. `U0001`

```
df <- data.frame(
        x = 1:3
        ,y = 1
        #,wthr = c("day-cloudy", "rain", "rain")
        ,wthr = c("\U0001f00d", "\U0001f001", "\U0001f003")
      )

plot_ly(
        data = df
        ,x = ~x
        ,y = ~y
        ,text = ~wthr
      ) %>% add_text(textfont = list(family = "weathericons"))
```

**Comment by pvictor** [comment]
I didn't find a solution to embed HTML in plotly's markers.
Good idea to use unicode, 2 things to change in your example:
- just prefix unicode with `"\u"`
- you need to add weather lib CSS dependencies to your widget

Here's an example : 

```r
df <- data.frame(
  x = 1:3
  ,y = 1
  #,wthr = c("day-cloudy", "rain", "rain")
  ,wthr = c("\Uf00d", "\Uf001", "\Uf003")
)

plot_ly(
  data = df
  ,x = ~x
  ,y = ~y
  ,text = ~wthr
) %>% 
  (function(x) {
    x$dependencies <- c(x$dependencies, list(weather_dependencies()))
    x
  }) %>%
  add_text(textfont = list(family = "weathericons")) 
```

But for some reason icon is not displayed correctly in tooltip.

**Comment by sactyr** [comment]
Awesome thank you! I don't need the tooltip for what I am working on but this is excellent. I did see references to dependencies in your source code but didn't think of loading them in the pipe. Cheers!
